spring.application.name=Micro_tech

spring.datasource.url=jdbc:postgresql://localhost:5432/mecro_tech

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8081
